version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    hostname: rabbit-check-host
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: unless-stopped
    volumes:
      - ./rabbit/rabbitmq-compose.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbit/01-credentials-definitions.json:/etc/rabbitmq/definitions/01-credentials-definitions.json
      - ./rabbit/02-queues-definitions.json:/etc/rabbitmq/definitions/02-queues-definitions.json
