server:
  port: 8083

service:
  id: state-service-client-1

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: document-check
    password: document-check
    virtual-host: document-check-host